# OpenAI
OPENAI_API_KEY = ""
OPENAI_EMBEDDING_MODEL = "text-embedding-ada-002"
NODE_PARSER_CHUNK_SIZE = 8000
NODE_PARSER_CHUNK_OVERLAP = 200

# Azure Cognitive Search
AZURE_SEARCH_ENDPOINT = ""
AZURE_SEARCH_ADMIN_KEY = ""
AZURE_SEARCH_INDEX_NAME = ""

# Azure OpenAI
AZURE_OPENAI_ENDPOINT = ""
AZURE_OPENAI_API_KEY = ""

# Azure Blob Storage
AZURE_STORAGE_ACCESS_KEY = ""
AZURE_STORAGE_CONTAINER = ""